---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 10s
  path: ./infrastructure/dev/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system