apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: buypass-certificate-https
 namespace: traefik
spec:
 acme:
   email: certificates-test@digdir.no
   # We use the staging server here for testing to avoid hitting
   server: https://api.test4.buypass.no/acme/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: certificate-https-issuer-account-key
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik
